version: "3.5"
services:
  zookeeper:
    image: confluent/zookeeper:latest
    container_name: zookeeper
    network_mode: "host"
    ports:
      - "2181:2181"
    # volumes:
    #   - ./config/kafka/zk.properties:/etc/kafka/zookeeper.properties

  kafka:
    image: confluent/kafka:0.10.0.0-cp1
    container_name: kafka
    network_mode: "host"
    environment:
      #- KAFKA_ADVERTISED_HOST_NAME=
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafdrop:
    image: thomsch98/kafdrop
    container_name: kafdrop
    network_mode: "host"
    environment:
      # yes localhost as its a client side app outsite of the docker network on your host
      - ZK_HOSTS=localhost:2181
      - LISTEN=9000
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
